-- ========================================================
-- SUPABASE DATABASE SETUP FOR YASH TIDKE PORTFOLIO
-- Project: https://ekcalqxxtcuqvhbcumrh.supabase.co
-- ========================================================

-- 1. Create 'messages' table for Contact Form submissions
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts on messages" 
ON public.messages FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow public select on messages" 
ON public.messages FOR SELECT TO public USING (true);


-- 2. Create 'reviews' table for Live Review & Feedback Wall
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'Visitor / Client',
    rating INT DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
    quote TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts on reviews" 
ON public.reviews FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow public select on reviews" 
ON public.reviews FOR SELECT TO public USING (true);


-- 3. Create 'projects' table for Portfolio Projects Showcase
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    full_description TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    tech JSONB DEFAULT '[]'::jsonb,
    image TEXT NOT NULL,
    github_url TEXT DEFAULT 'https://github.com/heyash-6',
    accent TEXT DEFAULT 'purple',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on projects" 
ON public.projects FOR SELECT TO public USING (true);

CREATE POLICY "Allow public inserts on projects" 
ON public.projects FOR INSERT TO public WITH CHECK (true);


-- ========================================================
-- SEED INITIAL DATA
-- ========================================================

-- Initial Reviews
INSERT INTO public.reviews (name, role, rating, quote) VALUES
('Alex Vance', 'Startup Founder', 5, 'Great communication and fast delivery — highly recommend! Yash understood our requirements instantly.'),
('Elena Rostova', 'E-Commerce Director', 5, 'Yash built our landing page in record time. The quality and futuristic aesthetic blew our team away!');

-- Initial Projects (Apex Edge & PulseHealth)
INSERT INTO public.projects (title, category, description, full_description, tags, tech, image, github_url, accent) VALUES
(
  'Apex Edge — Modern Corporate Web Presence',
  'Business Site',
  'Professional business website with dark glassmorphism layout, ultra-fast page load times, integrated service catalog, and contact flow.',
  'Engineered for modern businesses looking for a high-end dark aesthetic. Apex Edge combines glassmorphic UI elements with high performance scores across desktop and mobile devices.',
  '["Business Site", "Lead Gen", "Glassmorphism"]'::jsonb,
  '["React", "Tailwind CSS", "Lucide Icons", "Vite"]'::jsonb,
  'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
  'https://github.com/heyash-6',
  'cyan'
),
(
  'PulseHealth — AI Medical Web Dashboard',
  'Web App',
  'Clean, responsive healthcare telemetry dashboard displaying real-time analytics, patient metrics, and AI diagnostics interface.',
  'PulseHealth delivers a high-contrast dashboard UI designed for medical professionals. Focuses on data clarity, health metrics visualization, and rapid UI state updates.',
  '["Web App", "Healthcare", "Dashboard"]'::jsonb,
  '["React", "Tailwind CSS", "Recharts", "Lucide"]'::jsonb,
  'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
  'https://github.com/heyash-6',
  'purple'
);
